version: "3"
services:
  app:
    build:
      context: .
      dockerfile: .docker/Dockerfile
    links:
    - mysql
    environment:
    - DB_CONNECTION=mysql
    - DB_HOST=mysql
    - DB_PORT=3306
    - DB_DATABASE=short-url
    - DB_USERNAME=root
    - DB_PASSWORD=q123
    ports:
    - "80:80"
  mysql:
    image: mysql:5.7
    ports:
    - 3306:3306
    volumes:
    - ./.docker/initdb:/docker-entrypoint-initdb.d
    environment:
      MYSQL_DATABASE: short-url
      MYSQL_USER: root
      MYSQL_PASSWORD: q123
      MYSQL_ROOT_PASSWORD: q123